apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: traffic-harvester
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
  - name: shared-data
    namespace: ""
  environment:
    name: python3-9
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: traffic_harvester.main
    packageref:
      name: traffic-harvester-pkg
      namespace: ""
  requestsPerPod: 1
  resources: {}
