include:
- ./traffic-api/*
kind: ArchiveUploadSpec
name: traffic-api-lSBz

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: traffic-api
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python3-9
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://traffic-api-lSBz
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-14T07:11:14Z"
