include:
- ./sudo-api/sudo_api.py
- ./sudo-api/requirements.txt
- ./sudo-api/build.sh
kind: ArchiveUploadSpec
name: sudo-api-sudo-api-py-l704

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: sudo-api
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python3-9
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://sudo-api-sudo-api-py-l704
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-17T14:21:21Z"
