apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: traffic-freeway
spec:
  createingress: false
  functionref:
    functionweights: null
    name: traffic-freeway
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /traffic-freeway
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /traffic-freeway
