apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: air-quality-observations
spec:
  createingress: false
  functionref:
    functionweights: null
    name: air-quality-stations-observations
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /air-quality-stations/{station-id:[a-z0-9\-]+}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /air-quality-stations/{station-id:[a-z0-9\-]+}
