apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: sudo-vehicle
spec:
  createingress: false
  functionref:
    functionweights: null
    name: sudo-vehicle
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /sudo-vehicle
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /sudo-vehicle
