apiVersion: fission.io/v1
kind: TimeTrigger
metadata:
  creationTimestamp: null
  name: traffic-timer
spec:
  cron: '@every 1m'
  functionref:
    functionweights: null
    name: traffic-harvester
    type: name
