apiVersion: fission.io/v1
kind: TimeTrigger
metadata:
  creationTimestamp: null
  name: epa-harvester-trigger
spec:
  cron: '@every 1h'
  functionref:
    functionweights: null
    name: epa-harvester
    type: name
